### ISSUE TITLE
Update log location

### ISSUE THREAD

**Issue by danielballan** [NSLS-II-SMI/profile_collection#15]
After this initial deployment we changed the facility standard bluesky log location from `/var/log/*` to `/var/log/bluesky/*`. Needs change to beamline user `/.bashrc`, directory creation, and testing.

cc @mrakitin

**Comment by mrakitin** [comment]
These variables were originally set during the deployment (#12):
```bash
xf12id@xf12id-ws1:~$ tail -7 ~/.bashrc

# Bluesky env vars for logging:
export BLUESKY_LOG_FILE="/var/log/bluesky/bluesky.log"
export BLUESKY_IPYTHON_LOG_FILE="/var/log/bluesky/bluesky_ipython.log"
# needed to write files with group writing permissions in /var/log/bluesky.
umask 0002
```

I updated the playbooks issue description (https://github.com/NSLS-II/playbooks/issues/363), however a lot of erroneous TODO items were already distributed. To preserve the current state of the corresponding issues, the assignees should correct the task manually.

I propose closing this issue.

**Comment by danielballan** [comment]
Ah, very well. The error was in my edit to the TODOs then.
