### ISSUE TITLE
Amptek exporting file

### ISSUE THREAD

**Issue by gfreychet** [NSLS-II-SMI/profile_collection#16]
The exporting was tested and ran when only one amptek file was acquired inside a bps.count().
It turned out to failed when we are now acquiring several amptek files in the same databroker document, using bps.scan().

The error is coming from 98-exporting.py 
_ValueError: Wrong number of items passed 1208, placement implies 2                                                                                                                                                              
During handling of the above exception, another exception occurred:
ValueError: Shape of passed values is (8192, 1208), indices imply (8192, 2)
See /var/log/bluesky/bluesky.log for the full traceback__

The number 1208 here corresponds to 2xnumber of amptek images (2 for the fact that we are saving 1D array of energies as well as 1D array of data from Amptek).

So, I can imagine that the exporting code is expecting only 1 amptek dataset and we will just need to adapt it to handle several data point

**Comment by mrakitin** [comment]
I am on vacation this week, maybe @MikeHart85 can look at it meanwhile?

**Comment by MikeHart85** [comment]
What is the desired behavior in the case of multiple images?

It looks like the energies are always the same, is that correct? If so, should the counts be summed across the images for each energy? Or each image have a separate spectrum column, but shared energy column? Or separate csv files for each image? Something else?

**Comment by gfreychet** [comment]
We would like to save each spectrum column in a separate csv file, but add the energy column in every csv.
Ideally, it would read the number assign to the scan step and will save the csv file with the common sample name, but implement each filename by this scan step number

**Comment by mrakitin** [comment]
Thanks for looking at it, @MikeHart85. And thanks for more details, @gfreychet.

I think the callback should be triggered on each event then, so that a separate file is created with the names templated the same way as for Pilatus detectors, such as `<name>_0001.csv` (or more zeros as needed). Should we read the write_template string from Pilatus to make it more consistent?

**Comment by gfreychet** [comment]
Either we could read from Pilatus detectors or I purposely saved the name used by Pilatus in the start document (without the numbers afterward) and can use an independent counter (which at the end would be the same as pilatus) from the point position in the scan . Hope this makes sense.

**Comment by mrakitin** [comment]
I meant to use the template string which would define how many zeros we want to have in the zero-padded counter.
What about the situation with double triggering? I hope it will not break the counter between Pilatus and Amptek, but it's worth to validate/test.

**Comment by mrakitin** [comment]
Closed via #17.
